const KEY="rayy_assistant_v4";
const defaults={reminders:[],goals:[],completed:[],settings:{morningTime:"08:00",nightTime:"21:00",dayStart:"08:00",dayEnd:"22:00",theme:"system",notifyMorning:true,notifyNight:true,motivational:true}};
let data=JSON.parse(localStorage.getItem(KEY)||"null")||defaults;data={...defaults,...data,settings:{...defaults.settings,...(data.settings||{})}};let editId=null,editGoalId=null,calDate=new Date();
const $=id=>document.getElementById(id);function save(){localStorage.setItem(KEY,JSON.stringify(data))}function todayISO(){return iso(new Date())}function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}function dateObj(s){return new Date(s+"T12:00:00")}function fmtDate(s){return new Intl.DateTimeFormat(undefined,{weekday:"short",month:"short",day:"numeric"}).format(dateObj(s))}function fmtTime(t){if(!t)return"";let [h,m]=t.split(":");let d=new Date();d.setHours(+h,+m);return d.toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}function toast(s){$("toast").textContent=s;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",2200)}function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
$("todayLabel").textContent=new Intl.DateTimeFormat(undefined,{weekday:"long",month:"long",day:"numeric"}).format(new Date());
function dueOn(r,s){let d=dateObj(s),b=dateObj(r.date);if(d<b)return false;if(r.repeat==="none")return s===r.date;if(r.repeat==="daily")return true;if(r.repeat==="weekly")return d.getDay()===b.getDay();if(r.repeat==="monthly")return d.getDate()===b.getDate();if(r.repeat==="custom")return (r.days||[]).includes(d.getDay());return false}
function daysLeft(r){return Math.ceil((dateObj(r.date)-dateObj(todayISO()))/86400000)}function urgency(r){let left=daysLeft(r);if(r.repeat!=="none")return 2;if(left<0)return 0;if(left<=1)return 1;if(left<=3)return 2;return 3}
function openReminder(r=null){editId=r?.id||null;$("modalTitle").textContent=r?"Edit Reminder":"New Reminder";$("task").value=r?.task||"";$("date").value=r?.date||todayISO();$("time").value=r?.time||"09:00";$("category").value=r?.category||"University";$("priority").value=r?.priority||2;$("duration").value=r?.duration||30;$("repeat").value=r?.repeat||"none";$("location").value=r?.location||"";$("notes").value=r?.notes||"";$("sound").checked=r?.sound!==false;$("vibrate").checked=r?.vibrate!==false;renderDays(r?.days||[]);$("deleteReminder").style.display=r?"block":"none";$("modal").classList.add("open")}
function renderDays(active=[]){$("customDays").innerHTML=["S","M","T","W","T","F","S"].map((x,i)=>`<button data-day="${i}" class="${active.includes(i)?"on":""}">${x}</button>`).join("");$("customDays").querySelectorAll("button").forEach(b=>b.onclick=()=>b.classList.toggle("on"))}$("repeat").onchange=()=>$("customDays").classList.toggle("hidden",$("repeat").value!=="custom");$("addReminder").onclick=()=>openReminder();$("closeModal").onclick=()=>$("modal").classList.remove("open");
$("saveReminder").onclick=()=>{let task=$("task").value.trim(),date=$("date").value;if(!task||!date)return toast("Add a task and date first.");let r={id:editId||crypto.randomUUID(),task,date,time:$("time").value,category:$("category").value,priority:+$("priority").value,duration:Math.max(5,+$("duration").value||30),repeat:$("repeat").value,days:[...$("customDays").querySelectorAll(".on")].map(b=>+b.dataset.day),location:$("location").value,notes:$("notes").value,sound:$("sound").checked,vibrate:$("vibrate").checked,done:false};let i=data.reminders.findIndex(x=>x.id===r.id);if(i>=0)data.reminders[i]=r;else data.reminders.push(r);save();$("modal").classList.remove("open");render();toast("Saved.")};
$("deleteReminder").onclick=()=>{if(!editId)return;data.reminders=data.reminders.filter(r=>r.id!==editId);save();$("modal").classList.remove("open");render();toast("Reminder deleted.")};
function complete(id){let r=data.reminders.find(x=>x.id===id);if(!r)return;data.reminders=data.reminders.filter(x=>x.id!==id);data.completed.push({...r,completedAt:new Date().toISOString()});save();render();toast("Completed ✓")}
function render(){let all=data.reminders.filter(r=>dueOn(r,todayISO())).sort((a,b)=>(a.time||"99").localeCompare(b.time||"99")||a.priority-b.priority);let pri=all.filter(r=>r.priority===1||urgency(r)<=1);$("priorityList").innerHTML=pri.length?pri.map(cardHTML).join(""):"<div class='muted'>No urgent priorities.</div>";$("todayList").innerHTML=all.map(cardHTML).join("");$("empty").style.display=all.length?"none":"block";$("dayStatus").textContent=`${all.length} task${all.length===1?"":"s"} today · ${data.completed.filter(x=>x.completedAt?.slice(0,10)===todayISO()).length} completed`;renderBrief(all);renderNight();renderGoals();renderCalendar();renderWeekly();applyTheme()}
function cardHTML(r){let u=urgency(r),cls=u===0?"overdue":u===1?"urgent":u===2?"soon":"normal",left=r.repeat==="none"?(daysLeft(r)<0?"Overdue":daysLeft(r)===0?"Due today":`${daysLeft(r)}d left`):r.repeat;return `<div class="card rem ${cls}"><button class="check" onclick="complete('${r.id}')"></button><div class="grow"><h3>${esc(r.task)}</h3><div class="meta"><span class="cat">${esc(r.category)}</span> · ${r.time?fmtTime(r.time):"Any time"} · ${left} · ${r.duration||30} min</div>${r.location?`<div class="meta">📍 ${esc(r.location)}</div>`:""}${r.notes?`<div class="meta">${esc(r.notes)}</div>`:""}</div><div class="actions"><button class="small" onclick='openReminder(data.reminders.find(x=>x.id==="${r.id}"))'>✏️</button></div></div>`}
function renderBrief(all){let upcoming=data.reminders.filter(r=>r.repeat!=="none"||dateObj(r.date)>=dateObj(todayISO())).sort((a,b)=>a.date.localeCompare(b.date)||(a.time||"").localeCompare(b.time||"")).slice(0,6);$("morningBrief").innerHTML=`<div class="briefStats"><b>${all.length}</b> today · <b>${all.filter(r=>r.category==="University").length}</b> university · <b>${all.filter(r=>r.category==="Work").length}</b> work</div><div class="briefList">${all.slice(0,5).map(r=>`<div>• ${esc(r.task)} <span>${r.time?fmtTime(r.time):""}</span></div>`).join("")||"<div>You're clear. Use the free time intentionally.</div>"}</div><div class="aiTip">🧠 ${suggestion(all)}</div>`}
function suggestion(all){let urgent=all.filter(r=>urgency(r)<=1);if(urgent.length)return`Start with “${esc(urgent[0].task)}” — it is your most time-sensitive item.`;let uni=all.find(r=>r.category==="University");if(uni)return`Protect a focused block for “${esc(uni.task)}” before the day gets busy.`;return"You have room today. Choose one meaningful task and finish it."}
function renderNight(){let done=data.completed.filter(x=>x.completedAt?.slice(0,10)===todayISO()),remaining=data.reminders.filter(r=>dueOn(r,todayISO()));$("nightReview").innerHTML=`<div><b>${done.length}</b> completed today · <b>${remaining.length}</b> still open.</div><div class="aiTip">${remaining.length?`Tonight: move unfinished work deliberately instead of letting it pile up. Your next best step is <b>${esc(remaining.sort((a,b)=>a.priority-b.priority)[0]?.task||"reviewing tomorrow")}</b>.`:`Excellent. You finished today's active list. Protect your progress tomorrow.`}</div>`}
function openGoal(g=null){editGoalId=g?.id||null;$("goalModalTitle").textContent=g?"Edit Goal":"New Goal";$("goalName").value=g?.name||"";$("goalDate").value=g?.date||"";$("goalProgress").value=g?.progress||0;$("progressValue").textContent=(g?.progress||0)+"%";$("goalNotes").value=g?.notes||"";$("deleteGoal").style.display=g?"block":"none";$("goalModal").classList.add("open")}
$("addGoal").onclick=()=>openGoal();$("closeGoal").onclick=()=>$("goalModal").classList.remove("open");$("goalProgress").oninput=()=>$("progressValue").textContent=$("goalProgress").value+"%";$("saveGoal").onclick=()=>{let name=$("goalName").value.trim();if(!name)return toast("Add a goal first.");let g={id:editGoalId||crypto.randomUUID(),name,date:$("goalDate").value,progress:+$("goalProgress").value,notes:$("goalNotes").value};let i=data.goals.findIndex(x=>x.id===g.id);if(i>=0)data.goals[i]=g;else data.goals.push(g);save();$("goalModal").classList.remove("open");render();toast("Goal saved.")};$("deleteGoal").onclick=()=>{if(!editGoalId)return;data.goals=data.goals.filter(g=>g.id!==editGoalId);save();$("goalModal").classList.remove("open");render();toast("Goal deleted.")};
function renderGoals(){$("goalsList").innerHTML=data.goals.length?data.goals.map(g=>`<div class="goal" onclick='openGoal(data.goals.find(x=>x.id==="${g.id}"))'><div class="goalTop"><h2>${esc(g.name)}</h2><b>${g.progress}%</b></div><div class="bar"><i style="width:${g.progress}%"></i></div><div class="goalFoot"><span>${g.notes?esc(g.notes):"Tap to edit"}</span><span>${g.date?fmtDate(g.date):""}</span></div></div>`).join(""):"<div class='empty'>Add your first goal 🎯</div>";if(data.settings.motivational)$("quoteBox").innerHTML=`<div class="briefTitle">💬 Perspective</div><blockquote>${esc(quotes[new Date().getDate()%quotes.length].text)}</blockquote><cite>— ${esc(quotes[new Date().getDate()%quotes.length].author)}</cite><div class="tiny">Source: ${esc(quotes[new Date().getDate()%quotes.length].source)}</div>`;else $("quoteBox").innerHTML=""}
const quotes=[{text:"We are what we repeatedly do. Excellence, then, is not an act, but a habit.",author:"Aristotle",source:"Nicomachean Ethics, Book II (paraphrased/traditional attribution)"},{text:"It always seems impossible until it’s done.",author:"Nelson Mandela",source:"Commonly attributed to Mandela; attribution is disputed."},{text:"The secret of getting ahead is getting started.",author:"Mark Twain",source:"Attribution commonly reported; exact source uncertain."},{text:"Success is the sum of small efforts, repeated day in and day out.",author:"Robert Collier",source:"The Secret of Power, 1926"},{text:"He who has a why to live can bear almost any how.",author:"Friedrich Nietzsche",source:"Twilight of the Idols / later quotation tradition"}];
function renderCalendar(){let y=calDate.getFullYear(),m=calDate.getMonth();$("monthTitle").textContent=new Intl.DateTimeFormat(undefined,{month:"long",year:"numeric"}).format(calDate);let first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),html=["S","M","T","W","T","F","S"].map(x=>`<div class="dow">${x}</div>`).join("");for(let i=0;i<first;i++)html+="<div></div>";for(let d=1;d<=days;d++){let s=iso(new Date(y,m,d)),items=data.reminders.filter(r=>dueOn(r,s));html+=`<div class="day ${s===todayISO()?"today":""}"><b>${d}</b>${items.slice(0,3).map(r=>`<span class="dot u${urgency(r)}">${esc(r.task)}</span>`).join("")}</div>`}$("calendar").innerHTML=html}$("prevMonth").onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderCalendar()};$("nextMonth").onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderCalendar()};
function renderWeekly(){let start=new Date();start.setDate(start.getDate()-start.getDay());let html="";for(let i=0;i<7;i++){let d=new Date(start);d.setDate(start.getDate()+i);let s=iso(d),fixed=data.reminders.filter(r=>dueOn(r,s)).sort((a,b)=>(a.time||"").localeCompare(b.time||""));let free=fixed.length?"Use gaps between fixed commitments":"Open day — choose a goal block";html+=`<div class="planDay"><b>${new Intl.DateTimeFormat(undefined,{weekday:"short",month:"short",day:"numeric"}).format(d)}</b><span>${fixed.slice(0,2).map(r=>`${r.time?fmtTime(r.time)+" · ":""}${esc(r.task)}`).join(" | ")||"No fixed items"}</span><em>💡 ${free}</em></div>`}$("weeklyPlan").innerHTML=html}
function quick(){let s=$("quickInput").value.trim();if(!s)return;let lower=s.toLowerCase(),d=new Date();if(lower.includes("tomorrow"))d.setDate(d.getDate()+1);let date=iso(d),time="09:00",m=s.match(/(?:at\s+)?(\d{1,2})(?::(\d{2}))?\s*(am|pm)/i);if(m){let h=+m[1],mm=m[2]||"00";if(m[3].toLowerCase()==="pm"&&h<12)h+=12;if(m[3].toLowerCase()==="am"&&h===12)h=0;time=String(h).padStart(2,"0")+":"+mm}let due=s.match(/due\s+(monday|tuesday|wednesday|thursday|friday|saturday|sunday)/i);if(due){let names=["sunday","monday","tuesday","wednesday","thursday","friday","saturday"],target=names.indexOf(due[1].toLowerCase()),delta=(target-d.getDay()+7)%7;if(delta===0)delta=7;d.setDate(d.getDate()+delta);date=iso(d)}let dur=s.match(/(\d+)\s*(?:min|minutes|hour|hours)/i);let duration=dur?(+dur[1]*(/hour/i.test(dur[0])?60:1)):30;s=s.replace(/remind me/ig,"").replace(/tomorrow|today/ig,"").replace(/due\s+(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday)/ig,"").replace(/at\s+\d{1,2}(?::\d{2})?\s*(?:am|pm)/ig,"").replace(/for\s+\d+\s*(?:min|minutes|hour|hours)/ig,"").replace(/^\s*(to\s*)?/i,"").trim();openReminder({task:s,date,time,duration,repeat:"none",category:"University",priority:2});$("quickInput").value=""}
$("quickAdd").onclick=quick;$("quickInput").addEventListener("keydown",e=>{if(e.key==="Enter")quick()});
function openSettings(){for(let k of ["morningTime","nightTime","dayStart","dayEnd","theme","notifyMorning","notifyNight","motivational"]){if($(k))$(k).value!==undefined&&typeof $(k).value!=="undefined"&&$(k).type!=="checkbox"?$(k).value=data.settings[k]:$(k).checked=data.settings[k]}$("settingsModal").classList.add("open")}
$("settingsBtn").onclick=openSettings;$("closeSettings").onclick=()=>$("settingsModal").classList.remove("open");$("saveSettings").onclick=()=>{["morningTime","nightTime","dayStart","dayEnd","theme"].forEach(k=>data.settings[k]=$(k).value);["notifyMorning","notifyNight","motivational"].forEach(k=>data.settings[k]=$(k).checked);save();applyTheme();$("settingsModal").classList.remove("open");toast("Settings saved.")};
function applyTheme(){document.documentElement.dataset.theme=data.settings.theme}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{if(b.dataset.tab==="settings")return openSettings();document.querySelectorAll("nav button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(b.dataset.tab).classList.add("active")});
render();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");